### PR TITLE
Modular kernel build

### PR DESCRIPTION
**Pull request by mithrandir42**
Modular kernel build. Works on my build system. Kernel boots on gemini. Please try.

### CODE REVIEW

**Comment by adamboardman** [comment]
Most changes are as suggested from NS/Y to modular, there are however some other changes that I think should be an active/positive change decision.

**From not set to yes:**
CONFIG_TASKSTATS, CONFIG_TASK_DELAY_ACCT, CONFIG_TASK_IO_ACCOUNTING, CONFIG_CFG80211_DEFAULT_PS, CONFIG_INPUT_MOUSE, CONFIG_SERIO

**From yes to not set:**
CONFIG_CGROUP_MEM_RES_CTLR, CONFIG_PACKET_DIAG, CONFIG_UNIX_DIAG, CONFIG_INET_UDP_DIAG, CONFIG_IP6_NF_TARGET_MASQUERADE, CONFIG_NETLINK_DIAG

If anyone has any opinions on whether these are the right/wrong calls please tell us.

**Comment by mithrandir42** [comment]
TASK_DELAY_ACCT CONFIG_TASKSTATS, TASK_IO_ACCOUNTING are there for being able to run iotop. 
CONFIG_INPUT_MOUSE is needed for some usb mice/touchpads
CONFIG_SERIO gets selected by CONFIG_INPUT_MOUSE
CONFIG_CFG80211_DEFAULT_PS - wifi power saving as default, seems not to cause problems
The other options that got disabled might be remainings from starting with /proc/config.gz. At least these options are also not present in the initial config read from proc. Since these are present in the aeon6797_6m_n_halium_defconfig enabling should not hurt. Strange, that the config read from proc differs from the defconfig.

**Comment by adamboardman** [comment]
Thanks for the info, wifi power saving if it works would be very handy. Interesting to know which kernel you read from proc, an original planet one, or built from recent sources/apt? Also might be nice to compare to an original (and latest) planet android kernel.

I've got as far as being able to compile the kernel and modules (just the crossbuilder one from the packaging branch, build server still going) and it now fails at the install stage until you make a symlink:

depmod: ERROR: could not open directory /lib/modules/3.18.41: No such file or directory

The package has installed files to /lib/modules/3.18.41+/ which is clearly not quite the same name.

The symlink I had to make was: 'sudo ln -s /lib/modules/3.18.41+ /lib/modules/3.18.41'.

The other interesting thing is that its also installed into that folder some 'build' and 'source' links that link to non-existant folders on my device, is it usual to include those in the kernel package?

Kernel does indeed pickup drivers for random hardware now which is good.

**Comment by mithrandir42** [comment]
The missing "+" is strange. My build definitively had the "+" in the path. Maybe there is some variable we can use. I'll do some research later, maybe this evening. Regarding the build and source folders: I had a look onto a system with a distribution kernel. The build folder points to kernel headers and the source folder is not present there. So we can safely remove the source link (it is pointing to a valid location on your build machine, probably temporarily). For the build link, maybe we should include the kernel headers in this or a separate package (most distributions use separate packages, but I don' t think this is written in stone), so anyone can build a out of tree module without having the full kernel sources.

**Comment by mithrandir42** [comment]
Adam, what is the output of uname -r with your kernel? For mine it is 3.18.41+

**Comment by adamboardman** [comment]
Its the same, it might have been trying to run depmod with the old kernel whilst installing the new one (it blocked the install), now I'm running a new style kernel the names probably match... so maybe we need a clever little skip the depmod if the uname -r indicates we're not yet running the modular kernel? (do we need the depmod anyway? People kinda have to flash the kernel and reboot to make use of it?

**Comment by mithrandir42** [comment]
Did some research, the modules.dep gets generated on kernel build. But we need the depmod if there already are some custom modules present (otherwise modprobe or modules autoload won't work for these, the use case I have tried before inserting the step). In the usual update case the depmod will just work. For the use case with existing modules we should include the depmod step (most users likely forget to run it manually after upgrade and existing modules will likely work with most changes that I can imagine for the Gemini tree), but we should ignore the error if it fails. If we have the case of initial upgrade to the modular kernel (the case that seems to trigger the error) there won't be existing modules anyways.
This should work by changing the line to:
 depmod || :

**Comment by mithrandir42** [comment]
Forgot to answer one of the initial questions:
The configuration read from proc might have been from the initial TP1 kernel, since I have started with the modular kernel directly after receiving the Gemini. Afterwards I have regulary added the changes for the defconfig that you have added. Looks like I have missed https://github.com/gemian/gemini-linux-kernel-3.18/commit/96a5383d8796a6a067cdf29cd5566dd54a84f06f#diff-4caca49806e3b8b9cf0e79d256d11caf. So I think we should include the changes there.

**Comment by mithrandir42** [comment]
Maybe we should also include a hint to reboot after dd'ing.

**Comment by adamboardman** [comment]
I've added you to the project if you want to do any of the tidying up tasks.

**Comment by mithrandir42** [comment]
> I've added you to the project if you want to do any of the tidying up tasks.

Thanks, I'll see what I can do at the weekend. Won' t have spare time until Friday...

**Comment by mithrandir42** [comment]
> Most changes are as suggested from NS/Y to modular, there are however some other changes that I think should be an active/positive change decision.
> 
> **From not set to yes:**
> CONFIG_TASKSTATS, CONFIG_TASK_DELAY_ACCT, CONFIG_TASK_IO_ACCOUNTING, CONFIG_CFG80211_DEFAULT_PS, CONFIG_INPUT_MOUSE, CONFIG_SERIO
> 
> **From yes to not set:**
> CONFIG_CGROUP_MEM_RES_CTLR, CONFIG_PACKET_DIAG, CONFIG_UNIX_DIAG, CONFIG_INET_UDP_DIAG, CONFIG_IP6_NF_TARGET_MASQUERADE, CONFIG_NETLINK_DIAG
> 
> If anyone has any opinions on whether these are the right/wrong calls please tell us.

We could use modules for most of these, any objections?
CONFIG_CGROUP_MEM_RES_CTLR seems not be in Kconfig, so there is no point in enabling it.

For kernel headers I'd like to introduce a new branch "headers" for the header package.

**Comment by mithrandir42** [comment]
Also enabled CONFIG_IP6_NF_TARGET_NPT module here to have the complete set of NF_TARGET modules.
Imho, there are quite some more options we could use modules for. Since this requires more testing I suggest we try this later after releasing the first version.

**Comment by adamboardman** [comment]
Cool, I did build earlier in the week, so folk can install: gemian-modular-kernel
Let me know when your ready for another build (can also do test builds on a side repo).

I'd suggest a new package for headers rather than a new git branch? (ie you have two name.install files in the debian directory to specify which files go in which, plus other config changes)

**Comment by mithrandir42** [comment]
I think we are ready for another build. Builds, installs (had to install some dependencies and then do a apt-get install --fix-broken, but started with dpkg -i and not with apt install, so this might not be needed with the normal apt install) and boots. After installation I do not get planets penguin splash screen anymore, but the new "booting gemian". All changes I wanted to do for now are in. lxc-checkconfig now also tells that everything is there. Next will be the kernel headers package. For the future, I think there is quite some stuff that is currently built in that might be built as module. Maybe we should add some version information to the package name i.e. 3.18+ as part of the name with version number 0.2, so one can see from the outside what is in. What about adding a hint to the non modular kernel install, that there now also is a modular kernel and how it can be installed. Most people won't know about the option to use the modular kernel.

**Comment by mithrandir42** [comment]
Could you prepare the part with the install files? Don't know what to for this and how to trigger which gets used. Then afterwards I just have to change the header XXX.install file to get the kernel-headers package.

**Comment by adamboardman** [comment]
Nobody knows about the old kernel being there (except those that read the wiki - so we should update that), I'd suggest after we get a few early testers to check its all ok, we then just flip the meta package to pull in just the modular kernel. Then we just advertise the availability of the meta packages as a way to keep up to date with new things, folk just install one of the following: gemian-desktop-minimal, gemian-desktop-wifi or gemian-desktop. The reason I took the version number out of the kernel package is that there is no user choice in the available version, it provides no useful information to users.
Build started, eta 7-8 hours.

**Comment by adamboardman** [comment]
I've just pushed some draft install files+control file change, hope that helps.

**Comment by mithrandir42** [comment]
> I've just pushed some draft install files+control file change, hope that helps.

Thanks, how to tell debuild which package to build? Did not find useful information in the man page or around the web. When doing a "debuild -b -uc -us -nc" I just get :

dpkg-gencontrol: error: must specify package since control info has many (gemian-modular-kernel gemian-modular-kernel-headers)

**Comment by adamboardman** [comment]
Oops, yea usual auto-magic package building uses those install files, forgot that we were using a manual process for it. Had a bash at fixing it. FYI the latest native built kernel gave an error "cannot unlink 'debian/tmp/lib/modules/3.18.41+/source': No such file or directory". Made the assumption that it might be building packages with the cross build tools that drops that in? You should be using the packaging branch for that type of build.

**Comment by mithrandir42** [comment]
Hmm, looks like this build did not have the "+" in the path. Do you have a log of the build? 
Wondering why we have the extraversion in some builds and not in others.
Thought the packaging branch were for cross build?

**Comment by adamboardman** [comment]
Indeed, the cross build I did off the packaging branch had the + in it, and the native one from the qemu build lacks the + (after the update a 'dpkg -L gemian-modular-kernel' lists /lib/modules/3.18.41 as the path...) Just kicked off another build so we'll see if tomorrow morning if it makes a difference. Presumably you noticed I removed the CONFIG_CROSS_COMPILE from the modular config on the native branch, that is why I thought you had the branches confused.

**Comment by mithrandir42** [comment]
Kernel headers for the out of tree module build still are a problem. Currently trying the scripts/package/builddeb way. ( make O=../KERNEL_OUT -C ../gemini-linux-kernel-3.18 ARCH=arm64  CROSS_COMPILE=aarch64-linux-gnu- deb-pkg ) We'll see what comes out.

If it turns out to work, I think we have two options, either we use the script to generate the deb packages and forget our own packages (the mkbootimg step might be a showstopper here), or we gather the part of scripts/package/builddeb that extracts the headers and use it.

Before I was able to generate a headers package with which I have been able to compile modules by using the following lines in rules instead of the plain headers_install call:
        make O=$(CURDIR)/debian/tmp/usr/src/linux-headers-3.18 ARCH=arm64 gemini_modular_defconfig
        make O=$(CURDIR)/debian/tmp/usr/src/linux-headers-3.18 ARCH=arm64 modules_prepare
        make O=../KERNEL_OUT INSTALL_HDR_PATH=$(CURDIR)/debian/tmp/usr/src/linux-headers-3.18 ARCH=arm64 headers_install
        cp ../KERNEL_OUT/Module.symvers $(CURDIR)/debian/tmp/usr/src/linux-headers-3.18/

Unfortunately the built module loads and then results in the Gemini restarting.

**Comment by mithrandir42** [comment]
Same result with the kernel headers generated by 
make O=../KERNEL_OUT -C ../gemini-linux-kernel-3.18 ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- deb-pkg 
The "test" module can be built, but the Gemini reboots when the module gets loaded. Hard to tell if the reason is in the generated kernel-headers package (Module.symvers, etc.) or in the local build on the Gemini (different gcc version, etc.). Serial console output when loading the module might help, but I don't have a adapter to access the serial console on the Geminis Type-C port.

Which gcc version do you use for the jenkins build? If it is close to the Geminis version it might be worth a try with the lines above in the rules file. 

Other ideas?

gcc on my build machine: 5.4.0
gcc on the Gemini: 6.3.0

**Comment by mithrandir42** [comment]
Things are getting better. Using the kernel headers from the deb-pkg script and your kernel I have been able to build a module (had to edit include/generated/utsrelease.h to get rid of the "+" to statisfy the module version magic). Looks like the module built on the gemini fails with the kernel built with the older gcc version (or smth. else different in the build).

So I will try to adopt the kernel headers part from there to the Makefile.

**Comment by mithrandir42** [comment]
The headers generated by the four lines also work with your kernel build. So the modules compiled on the Gemini somehow are incompatible with my kernel build. So I have commited the lines for testing. Maybe you can start another build. Then I can install the packages and see if I can build a working kernel module on the Gemini with it.

Maybe it would be better to have the stuff in the Makefile, but I won't have spare time for this until next weekend, perhaps.

**Comment by mithrandir42** [comment]
Kernel headers are missing sth. My local built worked accidentally. Had a forgotten automount with kernel sources at the place where the symlink in our current headers points to...
Btw. we get the "+" in the version magic when there are uncommited changes...

**Comment by mithrandir42** [comment]
Hooray, I think I got the kernel headers working. Adam, could you please start a (hopefully) final test build?

**Comment by mithrandir42** [comment]
Thx for the build. The kernel works fine. Tried to build 3 external modules with the resulting kernel headers on the gemini. These also work. From my point of view we can promote this to the main repo and (unless you want to have some more testing) replace the kernel package with the modular package in the meta-package.

For future kernel work I'll also set up an lxc container on my build machine. Seems to be more flawless...

**Pull request merged**
